### ISSUE TITLE
nextjs-prisma starter is broken

### ISSUE THREAD

**Issue by louis-27** [railwayapp/templates#287]
![SCR-20220404-h3a](https://user-images.githubusercontent.com/48682663/161478663-d7e9b2c5-4563-488e-b8b3-4177c8687c78.png)

![SCR-20220404-h37](https://user-images.githubusercontent.com/48682663/161478696-f4761ed2-dcc9-41a5-9b9a-6fb9dfd0d22c.png)

Error Logs on Build:
```
ErrorCaptureStackTrace(err);
^
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/parser' is not defined by "exports" in /workspace/node_modules/next/node_modules/postcss/package.json
at new NodeError (node:internal/errors:371:5)
at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
at packageExportsResolve (node:internal/modules/esm/resolve:705:3)
at resolveExports (node:internal/modules/cjs/loader:482:36)
at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
at Function.Module._load (node:internal/modules/cjs/loader:778:27)
at Module.require (node:internal/modules/cjs/loader:999:19)
at require (node:internal/modules/cjs/helpers:102:18)
at Object.552 (/workspace/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11590)
at __nccwpck_require__ (/workspace/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
at Object.270 (/workspace/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:400)
at __nccwpck_require__ (/workspace/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
at Object.327 (/workspace/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:260)
at __nccwpck_require__ (/workspace/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:11735)
at Object.845 (/workspace/node_modules/next/dist/compiled/postcss-scss/scss-syntax.js:1:3733) {
code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
Node.js v17.5.0
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
ERROR: failed to build: exit status 1
ERROR: failed to build: executing lifecycle: failed with status code: 51
```

**Comment by JClackett** [comment]
Also having issues with prisma, how do you run the generate command on railway? whenever I do this it errors saying can't make directory node_modules

```
> @myapp@1.0.0 postinstall
> prisma generate
Prisma schema loaded from src/db/schema.prisma
Error:
✔ Generated Prisma Client (3.12.0 | library) to ./node_modules/@prisma/client in 105ms
Error: EACCES: permission denied, mkdir '/node_modules'
```

**Comment by FarazPatankar** [comment]
Closing this as we've moved the template to a [new repo](https://github.com/railwayapp-templates/nextjs-prisma). Feel free to open an issue there if you're still having trouble with the template.
